---
- name: Create directory for freifunk stub zones
  file:
    path: '/etc/unbound/{{ ff_stub_zones_dir }}/'
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'


- name: Build stub zones for all communities
  include_tasks: generate_stub.yml
  with_items: "{{ lookup('fileglob', ff_community_data_dir + '/*', wantlist=True) }}"
  loop_control:
    loop_var: ff_community_data_file
